// <auto-generated />
using BookStoreAppSpring.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookStoreAppSpring.Migrations
{
    [DbContext(typeof(BooksDbContext))]
    [Migration("20260205165710_addingBooksTableWithSeedData")]
    partial class addingBooksTableWithSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookStoreAppSpring.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BookId");

                    b.HasIndex("CategoryID");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "J.K. Rowling",
                            BookTitle = "Harry Potter and the Prisoner of Azkaban",
                            CategoryID = 2,
                            Description = "When the Knight Bus crashes through the darkness and screeches to a halt in front of him, it's the start of another far from ordinary year at Hogwarts for Harry Potter.",
                            ImgUrl = "",
                            Price = 22.91m
                        },
                        new
                        {
                            BookId = 2,
                            Author = "DK Travel",
                            BookTitle = "USA ANtional Parks: Land of Wonder",
                            CategoryID = 1,
                            Description = "The USA's National Parks truly are places of wonder: staggering landscapes of jaw-dropping dimensions and incredible diversity where you can stand on the very edge of civilzation. They are the earth's breathing spaces, precious places to conserve nature and wildlife for future preservation.",
                            ImgUrl = "",
                            Price = 16.80m
                        },
                        new
                        {
                            BookId = 3,
                            Author = "Scott Selikoff",
                            BookTitle = "OCP Oracle Certified Professional Java SE 17 Developer Study Guide: Exam 1Z0-829",
                            CategoryID = 3,
                            Description = "In the OCP Oracle Certified Professional Java SE 17 Developer Study Guide: Exam 1Z0-829, you'll find accessible and essential test prep material for the in-demand and practical OCP Java SE 17 Developer certification.",
                            ImgUrl = "",
                            Price = 36.99m
                        });
                });

            modelBuilder.Entity("BookStoreAppSpring.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Description = "This is the description for the Travel Category",
                            Name = "Travel"
                        },
                        new
                        {
                            CategoryId = 2,
                            Description = "This is the description for the Fiction Category",
                            Name = "Fiction"
                        },
                        new
                        {
                            CategoryId = 3,
                            Description = "This is the description for the Technology Category",
                            Name = "Technology"
                        });
                });

            modelBuilder.Entity("BookStoreAppSpring.Models.Book", b =>
                {
                    b.HasOne("BookStoreAppSpring.Models.Category", "category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");
                });
#pragma warning restore 612, 618
        }
    }
}
